const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");
const db = require("../../db");
const { authenticate, requireAdmin } = require("../../middleware/authenticate");

// Adjust these to your real brand colors if you have exact hex values.
const BRAND_NAVY = "#1e2a4a";
const BRAND_GOLD = "#c9962f";

async function logAdminAction(userId, action, ip, meta = {}) {
  try {
    await db.query(
      `INSERT INTO admin_audit_log (admin_id, action, ip_address, meta, created_at)
       VALUES ($1, $2, $3, $4, NOW())`,
      [userId, action, ip, JSON.stringify(meta)],
    );
  } catch (err) {
    console.error("Failed to write audit log:", err);
  }
}

function toCsv(rows, columns) {
  const escape = (val) => {
    if (val === null || val === undefined) return "";
    const str = String(val);
    if (str.includes(",") || str.includes('"') || str.includes("\n")) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const header = columns.map((c) => escape(c.label)).join(",");
  const lines = rows.map((row) =>
    columns.map((c) => escape(row[c.key])).join(","),
  );
  return [header, ...lines].join("\n");
}

function formatDate(value) {
  if (!value) return "";
  return new Date(value).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatCurrency(value) {
  if (value === null || value === undefined) return "";
  return `PHP ${Number(value).toLocaleString()}`;
}

function drawHeader(doc, title, adminUsername, filters) {
  doc
    .fillColor(BRAND_NAVY)
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("AuroraStay", 40, 40);

  doc
    .fillColor(BRAND_GOLD)
    .fontSize(10)
    .font("Helvetica")
    .text("Admin Report", 40, 64);

  doc
    .moveTo(40, 84)
    .lineTo(555, 84)
    .strokeColor(BRAND_GOLD)
    .lineWidth(2)
    .stroke();

  doc
    .fillColor(BRAND_NAVY)
    .fontSize(15)
    .font("Helvetica-Bold")
    .text(title, 40, 96);

  const metaLines = [
    `Generated: ${new Date().toLocaleString("en-US")}`,
    `Generated by: ${adminUsername || "admin"}`,
  ];
  if (filters) metaLines.push(filters);

  doc
    .fillColor("#666666")
    .fontSize(9)
    .font("Helvetica")
    .text(metaLines.join("   |   "), 40, 118);

  return 145; // Y position where table content should start
}

function drawFooter(doc, pageNumber) {
  doc
    .fillColor("#999999")
    .fontSize(8)
    .font("Helvetica")
    .text(`Page ${pageNumber}`, 40, 800, { align: "right", width: 515 });
}

function drawTable(doc, startY, columns, rows) {
  const pageBottom = 770;
  const rowHeight = 22;
  let y = startY;
  let pageNumber = 1;

  const totalWidth = 515;
  const colWidth = totalWidth / columns.length;

  function drawHeaderRow() {
    doc.rect(40, y, totalWidth, rowHeight).fill(BRAND_NAVY);
    doc.fillColor("#ffffff").fontSize(9).font("Helvetica-Bold");
    columns.forEach((col, i) => {
      doc.text(col.label, 44 + i * colWidth, y + 6, {
        width: colWidth - 8,
        ellipsis: true,
      });
    });
    y += rowHeight;
  }

  drawHeaderRow();

  rows.forEach((row, rowIndex) => {
    if (y + rowHeight > pageBottom) {
      drawFooter(doc, pageNumber);
      doc.addPage();
      pageNumber++;
      y = 40;
      drawHeaderRow();
    }

    if (rowIndex % 2 === 0) {
      doc.rect(40, y, totalWidth, rowHeight).fill("#f7f5f0");
    }

    doc.fillColor("#222222").fontSize(8.5).font("Helvetica");
    columns.forEach((col, i) => {
      const rawValue = row[col.key];
      const value = col.format ? col.format(rawValue) : (rawValue ?? "");
      doc.text(String(value), 44 + i * colWidth, y + 6, {
        width: colWidth - 8,
        ellipsis: true,
      });
    });

    y += rowHeight;
  });

  drawFooter(doc, pageNumber);
}

// --- Report definitions ---

const REPORTS = {
  listings: {
    title: "Listings Report",
    dateColumn: "l.created_at",
    columns: [
      { key: "title", label: "Title" },
      { key: "accommodation_type", label: "Type" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status" },
      { key: "created_at", label: "Created", format: formatDate },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let where = "";
      if (startDate) {
        params.push(startDate);
        where += ` AND l.created_at >= $${params.length}`;
      }
      if (endDate) {
        params.push(endDate);
        where += ` AND l.created_at <= $${params.length}`;
      }
      const result = await db.query(
        `SELECT l.id, l.title, l.accommodation_type, l.municipality, l.barangay,
                l.status, l.created_at
         FROM listings l
         WHERE 1=1 ${where}
         ORDER BY l.created_at DESC`,
        params,
      );
      return result.rows.map((row) => ({
        ...row,
        location: [row.barangay, row.municipality].filter(Boolean).join(", "),
      }));
    },
  },

  bookings: {
    title: "Bookings Report",
    dateColumn: "b.created_at",
    columns: [
      { key: "guest_name", label: "Guest" },
      { key: "title", label: "Listing" },
      { key: "check_in", label: "Check-in", format: formatDate },
      { key: "check_out", label: "Check-out", format: formatDate },
      { key: "status", label: "Status" },
      { key: "total_price", label: "Total", format: formatCurrency },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let where = "";
      if (startDate) {
        params.push(startDate);
        where += ` AND b.created_at >= $${params.length}`;
      }
      if (endDate) {
        params.push(endDate);
        where += ` AND b.created_at <= $${params.length}`;
      }
      const result = await db.query(
        `SELECT b.id, b.guest_name, l.title, b.check_in, b.check_out,
                b.guests_count, b.status, b.total_price, b.created_at
         FROM bookings b
         JOIN rooms r ON r.id = b.room_id
         JOIN listings l ON l.id = r.property_id
         WHERE 1=1 ${where}
         ORDER BY b.created_at DESC`,
        params,
      );
      return result.rows;
    },
  },

  owners: {
    title: "Owners Report",
    dateColumn: "ha.created_at",
    columns: [
      { key: "full_name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "accommodation_name", label: "Property" },
      { key: "municipality", label: "Municipality" },
      { key: "created_at", label: "Approved since", format: formatDate },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let where = "AND ha.status = 'approved'";
      if (startDate) {
        params.push(startDate);
        where += ` AND ha.created_at >= $${params.length}`;
      }
      if (endDate) {
        params.push(endDate);
        where += ` AND ha.created_at <= $${params.length}`;
      }
      const result = await db.query(
        `SELECT ha.id, ha.full_name, ha.email, ha.accommodation_name,
                ha.municipality, ha.created_at
         FROM host_applications ha
         WHERE 1=1 ${where}
         ORDER BY ha.created_at DESC`,
        params,
      );
      return result.rows;
    },
  },

  tourists: {
    title: "Tourists Report",
    dateColumn: "u.created_at",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "created_at", label: "Joined", format: formatDate },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let where = "";
      if (startDate) {
        params.push(startDate);
        where += ` AND u.created_at >= $${params.length}`;
      }
      if (endDate) {
        params.push(endDate);
        where += ` AND u.created_at <= $${params.length}`;
      }
      const result = await db.query(
        `SELECT u.id, u.first_name, u.last_name, u.email, u.created_at
         FROM users u
         WHERE u.id NOT IN (SELECT oid FROM host_applications WHERE status = 'approved')
         ${where}
         ORDER BY u.created_at DESC`,
        params,
      );
      return result.rows.map((row) => ({
        ...row,
        name: [row.first_name, row.last_name].filter(Boolean).join(" "),
      }));
    },
  },

  revenue: {
    title: "Revenue Report — Top Listings",
    dateColumn: "b.created_at",
    columns: [
      { key: "title", label: "Listing" },
      { key: "location", label: "Location" },
      { key: "booking_count", label: "Bookings" },
      { key: "revenue", label: "Confirmed Revenue", format: formatCurrency },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let where = "";
      if (startDate) {
        params.push(startDate);
        where += ` AND b.created_at >= $${params.length}`;
      }
      if (endDate) {
        params.push(endDate);
        where += ` AND b.created_at <= $${params.length}`;
      }
      const result = await db.query(
        `SELECT l.id, l.title, l.municipality, l.barangay,
                COUNT(b.id) AS booking_count,
                COALESCE(SUM(b.total_price) FILTER (WHERE b.status = 'confirmed'), 0) AS revenue
         FROM bookings b
         JOIN rooms r ON r.id = b.room_id
         JOIN listings l ON l.id = r.property_id
         WHERE 1=1 ${where}
         GROUP BY l.id, l.title, l.municipality, l.barangay
         ORDER BY revenue DESC`,
        params,
      );
      return result.rows.map((row) => ({
        ...row,
        location: [row.barangay, row.municipality].filter(Boolean).join(", "),
      }));
    },
  },

  growth: {
    title: "Growth Report — Monthly Trend",
    dateColumn: "created_at",
    columns: [
      { key: "month", label: "Month" },
      { key: "new_users", label: "New Users" },
      { key: "new_owners", label: "New Owners" },
      { key: "new_listings", label: "New Listings" },
    ],
    async fetch({ startDate, endDate }) {
      const params = [];
      let userWhere = "";
      let ownerWhere = "AND status = 'approved'";
      let listingWhere = "";

      if (startDate) {
        params.push(startDate);
        const p = `$${params.length}`;
        userWhere += ` AND created_at >= ${p}`;
        ownerWhere += ` AND created_at >= ${p}`;
        listingWhere += ` AND created_at >= ${p}`;
      }
      if (endDate) {
        params.push(endDate);
        const p = `$${params.length}`;
        userWhere += ` AND created_at <= ${p}`;
        ownerWhere += ` AND created_at <= ${p}`;
        listingWhere += ` AND created_at <= ${p}`;
      }

      const [users, owners, listings] = await Promise.all([
        db.query(
          `SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS count
           FROM users WHERE 1=1 ${userWhere} GROUP BY month ORDER BY month`,
          params,
        ),
        db.query(
          `SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS count
           FROM host_applications WHERE 1=1 ${ownerWhere} GROUP BY month ORDER BY month`,
          params,
        ),
        db.query(
          `SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS count
           FROM listings WHERE 1=1 ${listingWhere} GROUP BY month ORDER BY month`,
          params,
        ),
      ]);

      const map = new Map();
      const label = (d) =>
        new Date(d).toLocaleDateString("en-US", {
          month: "short",
          year: "numeric",
        });

      users.rows.forEach((r) => {
        const key = label(r.month);
        map.set(key, {
          month: key,
          new_users: Number(r.count),
          new_owners: 0,
          new_listings: 0,
        });
      });
      owners.rows.forEach((r) => {
        const key = label(r.month);
        const existing = map.get(key) || {
          month: key,
          new_users: 0,
          new_owners: 0,
          new_listings: 0,
        };
        existing.new_owners = Number(r.count);
        map.set(key, existing);
      });
      listings.rows.forEach((r) => {
        const key = label(r.month);
        const existing = map.get(key) || {
          month: key,
          new_users: 0,
          new_owners: 0,
          new_listings: 0,
        };
        existing.new_listings = Number(r.count);
        map.set(key, existing);
      });

      return Array.from(map.values());
    },
  },
};

// --- GET /api/admin/reports/types ---
router.get("/types", authenticate, requireAdmin, (req, res) => {
  res.json({
    types: Object.entries(REPORTS).map(([key, config]) => ({
      key,
      title: config.title,
    })),
  });
});

// --- GET /api/admin/reports/:type/csv ---
router.get("/:type/csv", authenticate, requireAdmin, async (req, res) => {
  const report = REPORTS[req.params.type];
  if (!report) return res.status(404).json({ message: "Unknown report type." });

  try {
    const { startDate, endDate } = req.query;
    const rows = await report.fetch({ startDate, endDate });
    const csv = toCsv(rows, report.columns);

    const filename = `${req.params.type}-report-${Date.now()}.csv`;
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(csv);

    logAdminAction(req.userId, "export_report_csv", req.ip, {
      type: req.params.type,
      startDate,
      endDate,
    });
  } catch (err) {
    console.error("CSV export failed:", err);
    res.status(500).json({ message: "Failed to generate CSV." });
  }
});

// --- GET /api/admin/reports/:type/pdf ---
router.get("/:type/pdf", authenticate, requireAdmin, async (req, res) => {
  const report = REPORTS[req.params.type];
  if (!report) return res.status(404).json({ message: "Unknown report type." });

  try {
    const { startDate, endDate } = req.query;
    const rows = await report.fetch({ startDate, endDate });

    const storedUser = req.userUsername || "admin";
    const filters = [
      startDate ? `From: ${startDate}` : null,
      endDate ? `To: ${endDate}` : null,
    ]
      .filter(Boolean)
      .join("   ");

    const filename = `${req.params.type}-report-${Date.now()}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      layout: "landscape",
    });
    doc.pipe(res);

    const startY = drawHeader(doc, report.title, storedUser, filters || null);
    drawTable(doc, startY, report.columns, rows);

    doc.end();

    logAdminAction(req.userId, "export_report_pdf", req.ip, {
      type: req.params.type,
      startDate,
      endDate,
    });
  } catch (err) {
    console.error("PDF export failed:", err);
    if (!res.headersSent) {
      res.status(500).json({ message: "Failed to generate PDF." });
    }
  }
});

module.exports = router;
